
class Telemetry:
    TIME = 0
    LAP_TIME = 1
    LAP_DISTANCE = 2
    OVERALL_DISTANCE = 3
    X_POSITION = 4
    Y_POSITION = 5
    Z_POSITION = 6
    SPEED_MPS = 7
    X_VELOCITY = 8
    Y_VELOCITY = 9
    Z_VELOCITY = 10
    X_ROLL = 11
    Y_ROLL = 12
    Z_ROLL = 13
    X_PITCH = 14
    Y_PITCH = 15
    Z_PITCH = 16
    SUSPENSION_POSITION_REAR_LEFT = 17
    SUSPENSION_POSITION_REAR_RIGHT = 18
    SUSPENSION_POSITION_FRONT_LEFT = 19
    SUSPENSION_POSITION_FRONT_RIGHT = 20
    SUSPENSION_VELOCITY_REAR_LEFT = 21
    SUSPENSION_VELOCITY_REAR_RIGHT = 22
    SUSPENSION_VELOCITY_FRONT_LEFT = 23
    SUSPENSION_VELOCITY_FRONT_RIGHT = 24
    WHEEL_VELOCITY_REAR_LEFT_MPS = 25
    WHEEL_VELOCITY_REAR_RIGHT_MPS = 26
    WHEEL_VELOCITY_FRONT_LEFT_MPS = 27
    WHEEL_VELOCITY_FRONT_RIGHT_MPS = 28
    THROTTLE = 29
    STEER = 30
    BRAKE = 31
    CLUTCH = 32
    GEAR = 33
    G_FORCE_LATERAL = 34
    G_FORCE_LONGITUDINAL = 35
    LAP = 36
    ENGINE_RPM = 37
    TOTAL_LAPS = 60
    TRACK_LENGTH = 61
    RACE_TIME = 62
    MAX_RPM = 63
    IDLE_RPM = 64
    MAX_GEARS = 65

    MPS_KMH_RATE = 3.59999999712

    GEAR_NEUTRAL = 0
    GEAR_REVERSE = 10

